# Ingress para Frontend (Kong)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: invest-portal-ingress
  namespace: ms-invest-portal
  labels:
    app: invest-portal
    external: "false"
    priority: "5"
spec:
  ingressClassName: kong
  rules:
  - host: invest-portal.hom-lionx.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: invest-portal
            port:
              number: 80
  tls:
  - hosts:
    - invest-portal.hom-lionx.com.br
    secretName: ms-invest-portal
